mappings:
  NAME1:
    target: NAME
    transformation: uppercase
  REGIO:
    target: REGION
    transformation: conditional_map
    conditions:
      NY: New York
  SPRAS:
    target: LANGUAGE
    transformation: conditional_map
    conditions:
      EN: English
      default: No Language
  LAND1:
    target: COUNTRY
    transformation: conditional_map
    conditions:
      US: United States
      CAN: Canada
