mappings:
 NAME1:
   target: COMPANY_NAME
   transformation: uppercase
 REGIO:
   target: REGION
   transformation: conditional_map
   conditions:
     "NY": "New York"
 SPRAS:
   target: LANGUAGE
   transformation: conditional_map
   conditions:
     "ER": "English"
     "": "Apple"   # Default value
 LAND1:
   target: COUNTRY
   transformation: conditional_map
   conditions:
     "US": "United States"
     "CAN": "Canada"
 KUNNR: CUSTOMER_ID
 ORT01: CITY
 PSTLZ: POSTAL_CODE
 STRAS: ADDRESS
 TELF1: PHONE_NUMBER
 LIFNR: VENDOR_ID